# Header
menu:
  Home: /
  Demo: /demo/
  Examples: /examples/
#  blog: /blog
#rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: bottom
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-56535258-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: