(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
        define("demoTemplates", ['jquery'], factory);
    } else if (typeof exports === 'object') {
        module.exports = factory(require('jquery'));
    } else {
        root.demoTemplates = factory(jQuery);
    }
})(this, function($) {
    var templates = {};
    templates.input = function (data, opts) {
        // generated by jQfy 1.3.7
        opts = $.extend({}, opts);
        data = $.extend({}, data);
        var $root = $('<div/>');
        
        var $div1 = $('<div/>')
            .attr("data-input-div", "")
            .appendTo($root);
        
        var $div2 = $('<div/>')
            .addClass("row")
            .appendTo($div1);
        
        var $div3 = $('<div/>')
            .addClass("col-md-6 col-xs-8")
            .appendTo($div2);
        
        var $div4 = $('<div/>')
            .addClass("input-group flat-bottom")
            .appendTo($div3);
        
        var $span1 = $('<span/>')
            .addClass("input-group-addon")
            .appendTo($div4);
        $span1.append(document.createTextNode("name:"));
        //      end $span1
        
        var $input1 = $('<input/>')
            .addClass("form-control")
            .attr("type", "text")
            .attr("data-name-input", "")
            .appendTo($div4);
        //      end $input1
        
        var $span2 = $('<span/>')
            .addClass("input-group-btn")
            .appendTo($div4);
        
        var $button1 = $('<button/>')
            .addClass("btn btn-danger")
            .attr("data-remove-btn", "")
            .appendTo($span2);
        $button1.append(document.createTextNode("x"));
        //       end $button1
        //      end $span2
        //     end $div4
        //    end $div3
        //   end $div2
        
        var $textarea1 = $('<textarea/>')
            .addClass("form-control flat-top-left")
            .attr("data-code", "")
            .appendTo($div1);
        //   end $textarea1
        //  end $div1
        
        // start script 1
        
            $input1.val(data.name);
            $textarea1.val(data.code);
            $button1.on('click',function(){
                output.remove();
                if(data.onRemove instanceof Function){
                    data.onRemove();
                }
            });
        
        //  end script 1
        
        // end $root
        var output = $root.contents();
        return output;
    };
    
    return templates;
});
